package polypro.UI;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import raven.chart.CurveLineChart;
import raven.chart.ModelChart;
import raven.chart.ModelData;

/**
 *
 * @author Tri Dung
 */
public class BieuDoDoanhThu extends javax.swing.JFrame {

	/**
	 * Creates new form BieuDoDoanhThu
	 */
	private static String driver = "com.mysql.cj.jdbc.Driver";
	private static String dburl = "jdbc:mysql://localhost:3306/Polypro";
	private static String username = "root";
	private static String password = "1234";

	public BieuDoDoanhThu() {
		initComponents();
		chart.addLegend("2023", Color.decode("#7b4397"), Color.decode("#dc2430"));
		chart.addLegend("2024", Color.decode("#acb6e5"), Color.decode("#86fde8"));
		chart.addLegend("2025", Color.decode("#e65c00"), Color.decode("#F9D423"));
		chart.addLegend("2026", Color.decode("#9796f0"), Color.decode("#fbc7d4"));
		setData();
	}

	void setData() {
		try {
			List<ModelData> list = new ArrayList<>();
			Class.forName(driver);
			Connection connection = DriverManager.getConnection(dburl, username, password);
			Statement st = connection.createStatement();
			String sql = "call sp_ThongKeDoanhThuTheoNamVaThang()";
			ResultSet rs = st.executeQuery(sql);
			while (rs.next()) {
				int Thang = rs.getInt("Thang");
				int nam2023 = rs.getInt("Nam2023");
				int nam2024 = rs.getInt("Nam2024");
				int nam2025 = rs.getInt("Nam2025");
				int nam2026 = rs.getInt("Nam2026");
				list.add(new ModelData(Thang, nam2023, nam2024, nam2025, nam2026));
			}
			rs.close();
			for (int i = list.size() - 1; 1 >= 0; i--) {
				ModelData md = list.get(i);
				chart.addData(new ModelChart(md.getMonth() + "",
						new double[] { md.getNam2023(), md.getNam2024(), md.getNam2025(), md.getNam2026() }));
			}

		} catch (Exception e) {
		}
		chart.start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		panelShadow1 = new raven.panel.PanelShadow();
		chart = new CurveLineChart();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(56, 56, 168));

		panelShadow1.setBackground(new java.awt.Color(34, 59, 68));
		panelShadow1.setColorGradient(new java.awt.Color(17, 37, 45));

		chart.setForeground(new java.awt.Color(255, 255, 255));
		chart.setFillColor(true);

		javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
		panelShadow1.setLayout(panelShadow1Layout);
		panelShadow1Layout
				.setHorizontalGroup(
						panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panelShadow1Layout.createSequentialGroup().addContainerGap()
										.addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, 598,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(16, Short.MAX_VALUE)));
		panelShadow1Layout
				.setVerticalGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelShadow1Layout.createSequentialGroup().addGap(14, 14, 14)
								.addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelShadow1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(panelShadow1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BieuDoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BieuDoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BieuDoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BieuDoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BieuDoDoanhThu().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private CurveLineChart chart;
	private raven.panel.PanelShadow panelShadow1;
	// End of variables declaration//GEN-END:variables
}
